/**
 * @file DecodedText.h
 * @brief Parse and expose fields from a decoded JS8 frame.
 *
 * The `DecodedText` helper parses the formatted string produced by the
 * decoder and exposes convenient accessors for common fields such as
 * SNR, time, frequency offset, message text, and directed message
 * components.
 * 
 * @author VK3ACF
 */

#ifndef DECODEDTEXT_H
#define DECODEDTEXT_H

#include "JS8.h"

#include <QString>
#include <QStringList>

/**
 * @class DecodedText
 * @brief Wraps a decoded frame and provides parsed accessors.
 *
 * Construct from a decoder `JS8::Event::Decoded` or from a raw frame
 * string. Provides methods to inspect whether the frame is a heartbeat,
 * a directed message, a compound call, and to retrieve individual
 * message words.
 */
class DecodedText {
  public:
    /**
     * @brief Construct from a decoder event record.
     */
    explicit DecodedText(JS8::Event::Decoded const &);

    /**
     * @brief Construct from a raw decoded frame string.
     * @param frame Raw decoded text.
     * @param bits Number of decoded bits.
     * @param submode Submode index.
     */
    explicit DecodedText(QString const &frame, int bits, int submode);

    // Inline accessors

    /** Number of bits decoded. */
    int bits() const { return bits_; }

    /** Compound calls, if present. */
    QString compoundCall() const { return compound_; }

    /** Tokenized directed message components. */
    QStringList directedMessage() const { return directed_; }

    /** Time offset (seconds) between expected and observed frame boundary. */
    float dt() const { return dt_; }

    /** Extra metadata string from the decoded frame. */
    QString extra() const { return extra_; }

    /** Original decoded frame string. */
    QString frame() const { return frame_; }

    /** Frame type identifier (protocol-specific). */
    quint8 frameType() const { return frameType_; }

    /** Frequency offset in Hz from nominal. */
    int frequencyOffset() const { return frequencyOffset_; }

    /** Whether this frame used the alternate encoding. */
    bool isAlt() const { return isAlt_; }

    /** True when the decoded frame contains a compound call. */
    bool isCompound() const { return !compound_.isEmpty(); }

    /** True when this is a directed message. */
    bool isDirectedMessage() const { return directed_.length() > 2; }

    /** True when the frame represents a heartbeat. */
    bool isHeartbeat() const { return isHeartbeat_; }

    /** True when the decoder flagged the frame as low confidence. */
    bool isLowConfidence() const { return isLowConfidence_; }

    /** Message text extracted from the frame. */
    QString message() const { return message_; }

    /** Signal-to-noise ratio in dB (integer). */
    int snr() const { return snr_; }

    /** Submode index used for decoding. */
    int submode() const { return submode_; }

    /**
     * @brief Timestamp as produced by the decoder (use decode_time() to split).
     */
    int time() const { return time_; }

    // Accessors

    /**
     * @brief Tokenize message into words.
     * @return List of message words.
     */
    QStringList messageWords() const;

    /**
     * @brief Return a human-readable representation of the decoded frame.
     */
    QString string() const;

  private:
    // Unpacking strategies, attempted in order until one succeeds.

    bool tryUnpackFastData(QString const &);
    bool tryUnpackData(QString const &);
    bool tryUnpackHeartbeat(QString const &);
    bool tryUnpackCompound(QString const &);
    bool tryUnpackDirected(QString const &);

    static constexpr std::array unpackStrategies = {
        &DecodedText::tryUnpackFastData, &DecodedText::tryUnpackData,
        &DecodedText::tryUnpackHeartbeat, &DecodedText::tryUnpackCompound,
        &DecodedText::tryUnpackDirected};

    // Core constructor called by public constructors.
    DecodedText(QString const &frame, int bits, int submode,
                bool isLowConfidence,
                int time, // As generated by code_time() in commons.h.
                int frequencyOffset, float snr, float dt);

    // Data members ** ORDER DEPENDENCY **

    quint8 frameType_;
    QString frame_;
    bool isAlt_;
    bool isHeartbeat_;
    bool isLowConfidence_;
    QString compound_;
    QStringList directed_;
    QString extra_;
    QString message_;
    int bits_;
    int submode_;
    int time_;
    int frequencyOffset_;
    int snr_;
    float dt_;
};

#endif // DECODEDTEXT_H
