permissions:
  contents: read
  attestations: write
  id-token: write
  
name: CI Build for MacOS 26 Arm64 (M1 and higher)

on: 
  workflow_dispatch: 
  pull_request:
  workflow_call:
    inputs:
      build-type:
        description: 'Build type (Debug/Release)'
        required: false
        type: string
        default: 'Release'
      release-ver:
        description: 'Release Version (v2.5.0)'
        required: false
        type: string      
        default: 'v2.5.0'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_macos-latest:
    runs-on: macOS-26
    permissions: write-all

    steps:
    - uses: actions/checkout@v6

    - name: Create our own var with the ImageOS value for cache use
      id: which-os
      run: |
        export ImageOS=$(sw_vers -productVersion)
        echo "thisos=$ImageOS" >> $GITHUB_OUTPUT

    - name: Grab build dependeneces
      run: |
        curl --location --output /tmp/js8lib2.6-MacOS_AppleSilicon_Qt.tar.gz https://github.com/JS8Call-improved/JS8Call-improved/releases/download/lib%2F2.6/js8lib2.6-MacOS_AppleSilicon_Qt.tar.gz
        cd /tmp
        tar zxf /tmp/js8lib2.6-MacOS_AppleSilicon_Qt.tar.gz
        sudo mv /tmp/js8lib /usr/local/js8lib

        curl --location --output /tmp/ffmpeg_MacOS_arm64.tar.gz https://github.com/JS8Call-improved/JS8Call-improved/releases/download/lib%2F2.6/ffmpeg_MacOS_arm64.tar.gz
        tar zxf /tmp/ffmpeg_MacOS_arm64.tar.gz
        sudo mv /tmp/ffmpeg /usr/local/ffmpeg
      
    - name: Build JS8Call
      run: |
        mkdir -p ./build && cd ./build
        cmake -DCMAKE_PREFIX_PATH="/usr/local/js8lib" ..
        make

    - name: Create DMG
      run: hdiutil create -volname "JS8Call-improved.dmg" -srcfolder "build/JS8Call.app" -format UDZO "JS8Call-improved.dmg"
      
    - name: Attestation (Release Only)
      if: ${{ inputs.release-ver }}
      uses: actions/attest-build-provenance@v3
      with:
        subject-path: '${{ github.workspace }}/JS8Call-improved.dmg'
        
    - name: Upload Artifact (Release build)
      if: ${{ inputs.release-ver }}
      uses: actions/upload-artifact@v6
      with:
        name: "JS8call-improved_${{ inputs.release-ver }}_${{ runner.arch }}_macos26.dmg"
        path: /Users/runner/work/JS8Call-improved/JS8Call-improved/JS8Call-improved.dmg

    - name: Upload Artifact (CI build)
      if: ${{ !inputs.release-ver }}
      uses: actions/upload-artifact@v6
      with:
        name: "JS8call-improved_devel_${{ runner.arch }}_macos26.dmg"
        path: /Users/runner/work/JS8Call-improved/JS8Call-improved/JS8Call-improved.dmg
