name: Secrets testing

on: 
  pull_request:
  workflow_dispatch: 
    inputs:
      build-type:
        description: 'Build type (Debug/Release)'
        required: false
        type: string
        default: 'Release'
      release-ver:
        description: 'Release Version (v2.5.0)'
        required: false
        type: string
        default: 'v2.5.0'
      environment:
        description: 'Environment to run in'
        type: environment
        required: true

jobs:
  build_windows-2025:
    runs-on: windows-2025
    permissions: write-all

    steps:
    - run: git config --global core.autocrlf input
    - uses: actions/checkout@v5

    - name: Get secrets
      shell: pwsh
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        CODE_SIGNING_PFX_BASE64: ${{ secrets.CI_CODE_SIGNING_PFX_BASE64 }}
        PFX_CERTIFICATE_PASSWORD: ${{ secrets.CI_PFX_CERTIFICATE_PASSWORD }}
        R-CODE_SIGNING_PFX_BASE64: ${{ secrets.RELEASE_CODE_SIGNING_PFX_BASE64 }}
        R-PFX_CERTIFICATE_PASSWORD: ${{ secrets.RELEASE_PFX_CERTIFICATE_PASSWORD }}
      run: |
        echo "${{ secrets.CI_CODE_SIGNING_PFX_BASE64 }}" > 'D:/a/JS8Call-improved/cert.base64'
        echo "${{ secrets.RELEASE_CODE_SIGNING_PFX_BASE64 }}" > 'D:/a/JS8Call-improved/cert-re.base64'
        certutil -decode 'D:/a/JS8Call-improved/cert.base64' 'D:/a/JS8Call-improved/certificate.pfx'
        certutil -decode 'D:/a/JS8Call-improved/cert-re.base64' 'D:/a/JS8Call-improved/certificate.pfx'
      continue-on-error: false

      
