name: Format check on Linux Ubuntu
run-name: ${{ (github.event.pull_request.title) || 'CI' }} Format check on Linux Ubuntu

on:
  [pull_request]

jobs:
  clang_format_check:
    runs-on: ubuntu-latest
    name: Check Code Style
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v5
    
    - name: Install minimum required dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format-20

    - name: Run clang-format dry-run
      run: clang-format-20 --Werror --dry-run --style='{BasedOnStyle: LLVM, IndentWidth: 4}' JS8*/*.h JS8*/*.cpp
