; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "JS8Call-improved"
#define MyAppVersion "2.5.0"
#define MyAppPublisher "JS8Call-improved"
#define MyAppURL "https://www.js8call-improved.com/"
#define MyAppExeName "JS8Call-improved.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5B3F1070-8CE9-41A5-8F93-E5445849F7BC}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=JS8Call-improved-250
SolidCompression=yes
; WizardStyle introduced in 6.6.x, Github has 6.5.4
;WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\generic\*"; DestDir: "{app}\generic"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\iconengines\*"; DestDir: "{app}\iconengines"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\imageformats\*"; DestDir: "{app}\imageformats"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\multimedia\*"; DestDir: "{app}\multimedia"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\networkinformation\*"; DestDir: "{app}\networkinformation"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\platforms\*"; DestDir: "{app}\platforms"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\styles\*"; DestDir: "{app}\styles"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\tls\*"; DestDir: "{app}\tls"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\avcodec-61.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\avformat-61.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\avutil-59.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\D3Dcompiler_47.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\libhamlib-4.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\libusb-1.0.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\opengl32sw.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Multimedia.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Network.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6SerialPort.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Svg.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\swresample-5.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\kj4ct\Downloads\JS8call-improved_devel_X64_win64\swscale-8.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


