name: Cleanup old workflow runs
permissions:
  actions: write
on:
  schedule:
    - cron: '0 0 * * 0'  # weekly, Sunday midnight
  workflow_dispatch:      # allows manual trigger from Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: Mattraks/delete-workflow-runs@0cf693bc9909e5e867ee8f27b813224ba862939c
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 30
